whitelist_rules:
  - comma
  - empty_parameters
  - trailing_comma
  - vertical_whitespace
  - trailing_whitespace
  - opening_brace
  - comment_spacing
  - colon
  - control_statement
  - no_space_in_method_call
  - empty_parentheses_with_trailing_closure
  - trailing_newline
  - operator_usage_whitespace
  - closure_spacing
  - void_return
  - unneeded_parentheses_in_closure_argument
  - modifier_order
  - literal_expression_end_indentation
  - unused_closure_parameter
  - legacy_constructor
  - empty_enum_arguments
  - strong_iboutlet

trailing_comma:
  mandatory_comma: true

vertical_whitespace:
  max_empty_lines: 2

included:
  - <ProjectFolder>
